// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SherplexTickets.Infrastructure.Data;

#nullable disable

namespace SherplexTickets.Infrastructure.Migrations
{
    [DbContext(typeof(SherplexTicketsDbContext))]
    [Migration("20240316181249_RefacturingAndAddSeed")]
    partial class RefacturingAndAddSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Димитър Димов"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Иван Вазов"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Паисий Хилендарски"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Димитър Талев"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Алеко Константинов"
                        });
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current Book's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasComment("The current Book's Author Identifier");

                    b.Property<int>("CoverTypeId")
                        .HasColumnType("int")
                        .HasComment("The current Book's CoverType's Identifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The current Book's Description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The current Book's cover image url");

                    b.Property<int>("Pages")
                        .HasColumnType("int")
                        .HasComment("The current Book's Pages Count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The current Book's Title");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int")
                        .HasComment("The date on which the curent Book was published");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CoverTypeId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CoverTypeId = 1,
                            Description = "Романът „Тютюн“ разказва за страстите, сблъсъците и разочарованията на тютюневите фермери в България през края на 19-и началото на 20 век. Главният герой, Тодор Гълъбов, се опитва да се пребори с лошата дола на съдбата и да изгради бъдеще за семейството си в условията на социални и икономически проблеми.",
                            ImageUrl = "@---",
                            Pages = 400,
                            Title = "Тютюн",
                            YearPublished = 1951
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CoverTypeId = 1,
                            Description = "„Под игото“ е роман от Иван Вазов, който разказва за борбата на българския народ за свобода от османско владичество. Книгата проследява историята на героите в едно село през времето на Априлското въстание.",
                            ImageUrl = "@---",
                            Pages = 280,
                            Title = "Под игото",
                            YearPublished = 1888
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CoverTypeId = 2,
                            Description = "„История славянобългарска“ е творба на Паисий Хилендарски, която се смята за първата българска историографска книга. В нея се описва историята и културното развитие на българския народ.",
                            ImageUrl = "@---",
                            Pages = 150,
                            Title = "История славянобългарска",
                            YearPublished = 1762
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CoverTypeId = 1,
                            Description = "„Железният светилник“ е роман на Димитър Талев, който разказва за историята на едно българско село във времето на Освобождението. Книгата проследява събитията и промените, които преминава селото и неговите обитатели.",
                            ImageUrl = "@---",
                            Pages = 320,
                            Title = "Железният светилник",
                            YearPublished = 1937
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CoverTypeId = 1,
                            Description = "„Бай Ганьо“ е сатиричен роман на Алеко Константинов, който разказва за приключенията на българина Бай Ганьо в ранните години на 20 век. Книгата представлява портрет на типичния българин от тоя период - обаятелен, амбициозен, но и смешен поради своите недостатъци и характеристични черти на поведение.",
                            ImageUrl = "@---",
                            Pages = 240,
                            Title = "Бай Ганьо",
                            YearPublished = 1895
                        });
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current Book Review's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasComment("The current Book's Identifier");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The current Book Review's Description");

                    b.Property<int>("Rate")
                        .HasColumnType("int")
                        .HasComment("The current Book Review's Rate");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The current Book Review's Title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The current User's Identifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("BookReviews");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.CoverType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current CoverType's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The current CoverType's Name");

                    b.HasKey("Id");

                    b.ToTable("CoverTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мека"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Твърда"
                        });
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.GenreOfBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current Movie Genre's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("The current Movie Genre's Name");

                    b.HasKey("Id");

                    b.ToTable("GenreOfBooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Художествена литература"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Българска литература"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Българска класика"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Световна класика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Криминален роман"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Фантастика"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Любовен роман"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Исторически роман"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Хумористична проза"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Роман"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Разкази"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Поезия"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Публицистика"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Биографична литература"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Биографии"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Автобиографии"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Пътеводители"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Техническа литература"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Образование"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Бизнес и Икономика"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Кулинария"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Диети"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Йога"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Религия и митология"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Философия"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Речници и разговорници"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Книги на други езици"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Детска литература"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Хорър"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Новели"
                        });
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.BookStores.BookStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current BookStore's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ClosingTime")
                        .HasColumnType("datetime2")
                        .HasComment("The current BookStore's Closing Time");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The current BookStore's Mobile Contact");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The current BookStore's Image Url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The current BookStore's Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The current BookStore's Name");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("datetime2")
                        .HasComment("The current BookStore's Opening Time");

                    b.HasKey("Id");

                    b.ToTable("BookStores");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Carts.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("The current User's Identifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.BookMapping.BookBookStore", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasComment("The current Book's Identifier");

                    b.Property<int>("BookStoreId")
                        .HasColumnType("int")
                        .HasComment("The current BookStore's Identifier");

                    b.HasKey("BookId", "BookStoreId");

                    b.HasIndex("BookStoreId");

                    b.ToTable("BookBookStores");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.BookMapping.BookCart", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int")
                        .HasComment("The current Book's Identifier");

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasComment("The current Cart's Identifier");

                    b.HasKey("BookId", "CartId");

                    b.HasIndex("CartId");

                    b.ToTable("BookCarts");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.BookMapping.GenreGenreOfBook", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("GenreId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("GenresGenresOfBooks");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            BookId = 1
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 1
                        },
                        new
                        {
                            GenreId = 1,
                            BookId = 2
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 2
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 3
                        },
                        new
                        {
                            GenreId = 3,
                            BookId = 3
                        },
                        new
                        {
                            GenreId = 2,
                            BookId = 4
                        },
                        new
                        {
                            GenreId = 4,
                            BookId = 4
                        },
                        new
                        {
                            GenreId = 1,
                            BookId = 5
                        },
                        new
                        {
                            GenreId = 7,
                            BookId = 5
                        },
                        new
                        {
                            GenreId = 9,
                            BookId = 5
                        });
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.MoviesMaping.ActorMovie", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int")
                        .HasComment("The current Actor Identifier");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("The current Movie Identifier");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("ActorsMovies");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.MoviesMaping.GenreGenreOfMovie", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("The current Genre's Identifier");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("The current Movie's Identifier");

                    b.HasKey("GenreId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("GenresMovies");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.MoviesMaping.MovieMovieTheater", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("The current Movie's Identifier");

                    b.Property<int>("MovieTheaterId")
                        .HasColumnType("int")
                        .HasComment("The current MovieTheater's Identifier");

                    b.HasKey("MovieId", "MovieTheaterId");

                    b.HasIndex("MovieTheaterId");

                    b.ToTable("MoviesMoviesTheaters");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current Actor's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("The current Actor's FirstName");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.GenreOfMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current Movie Genre's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GenreOfMovieId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasComment("The current Movie Genre's Name");

                    b.HasKey("Id");

                    b.HasIndex("GenreOfMovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Екшън"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Приключенски"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Комедия"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Драма"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ужаси"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Фентъзи"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Научна фантастика"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Трилър"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Криминален"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Документален"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Романтичен"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Исторически"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Военен"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Анимация"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Мистерия"
                        });
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current Movie's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("The current Movie's Description");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int")
                        .HasComment("The current Movie's Director Identifier");

                    b.Property<int>("MovieWhatchTime")
                        .HasColumnType("int")
                        .HasComment("The current Movie's Movie Watch Time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("The current Movie's Title");

                    b.Property<string>("URLImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The current Movie's URLImage");

                    b.Property<DateTime>("YearPublished")
                        .HasColumnType("datetime2")
                        .HasComment("The date on which the curent Movie was published");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.MovieTheaters.MovieTheater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current MovieTheater's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ClosingTime")
                        .HasColumnType("datetime2")
                        .HasComment("The current MovieTheater's Closing Time");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The current MovieTheater's Mobile Contact");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The current MovieTheater's Image Url");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("The current MovieTheater's Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("The current MovieTheater's Name");

                    b.Property<DateTime>("OpeningTime")
                        .HasColumnType("datetime2")
                        .HasComment("The current MovieTheater's Opening Time");

                    b.HasKey("Id");

                    b.ToTable("MovieTheater");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The current Ticket's Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasComment("The current Movie's Identifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The current Ticket's Price");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasComment("The current Ticket's PurchaseDate");

                    b.HasKey("TicketId");

                    b.HasIndex("MovieId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.Book", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Books.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Books.CoverType", "CoverType")
                        .WithMany("Books")
                        .HasForeignKey("CoverTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("CoverType");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.BookReview", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Books.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Carts.Cart", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.BookMapping.BookBookStore", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Books.Book", "Book")
                        .WithMany("BooksBookStores")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.BookStores.BookStore", "BookStore")
                        .WithMany("BooksBookStores")
                        .HasForeignKey("BookStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BookStore");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.BookMapping.BookCart", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Books.Book", "Book")
                        .WithMany("BooksCarts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Carts.Cart", "Cart")
                        .WithMany("BooksCarts")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.BookMapping.GenreGenreOfBook", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Books.Book", "Book")
                        .WithMany("GenresGenresOfBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Books.GenreOfBook", "Genre")
                        .WithMany("GenresMovies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.MoviesMaping.ActorMovie", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.Actor", "Actor")
                        .WithMany("ActorsMovies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", "Movie")
                        .WithMany("ActorsMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.MoviesMaping.GenreGenreOfMovie", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.GenreOfMovie", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Mappings.MoviesMaping.MovieMovieTheater", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.MovieTheaters.MovieTheater", "MovieTheater")
                        .WithMany("MoviesMoviesTheaters")
                        .HasForeignKey("MovieTheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("MovieTheater");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.GenreOfMovie", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.GenreOfMovie", null)
                        .WithMany("GenresMovies")
                        .HasForeignKey("GenreOfMovieId");

                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", null)
                        .WithMany("Genres")
                        .HasForeignKey("MovieId");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Ticket", b =>
                {
                    b.HasOne("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.Book", b =>
                {
                    b.Navigation("BooksBookStores");

                    b.Navigation("BooksCarts");

                    b.Navigation("GenresGenresOfBooks");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.CoverType", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Books.GenreOfBook", b =>
                {
                    b.Navigation("GenresMovies");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.BookStores.BookStore", b =>
                {
                    b.Navigation("BooksBookStores");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Carts.Cart", b =>
                {
                    b.Navigation("BooksCarts");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.Actor", b =>
                {
                    b.Navigation("ActorsMovies");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.GenreOfMovie", b =>
                {
                    b.Navigation("GenresMovies");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.Movies.Movie", b =>
                {
                    b.Navigation("ActorsMovies");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("SherplexTickets.Infrastructure.Data.Models.MovieTheaters.MovieTheater", b =>
                {
                    b.Navigation("MoviesMoviesTheaters");
                });
#pragma warning restore 612, 618
        }
    }
}
